root = "."
tmp_dir = "/tmp/air"

[build]
  cmd = "go build -o /tmp/air/server ./cmd/server"
  bin = "/tmp/air/server"
  include_ext = ["go"]
  exclude_dir = ["vendor"]
  delay = 500

[log]
  time = false
